### PR TITLE
Add the correct matches function

### PR DESCRIPTION
**Pull request by miltechniks**
There was an error, as there has been some old code which wasn't adjusted as far as I've seen it.

### CODE REVIEW

**Comment by djschilling** [comment]
@miltechniks which error does this fix?

**Comment by miltechniks** [comment]
@djschilling We found this error in our Logs when trying to attach a gitlab-Instance to the LDAP-Wrapper:
```Jan 31 21:36:27 feg-ldap-02 ctldap[2486]: [ERROR] xxxxx - Error while retrieving users:
Jan 31 21:36:27 feg-ldap-02 ctldap[2486]: Error: ext match implementation missing
Jan 31 21:36:27 feg-ldap-02 ctldap[2486]:     at ExtensibleFilter.matches (/home/ctldap/ctldap-ms/node_modules/ldap-filter/lib/ext_filter.js:81:9)
Jan 31 21:36:27 feg-ldap-02 ctldap[2486]:     at /home/ctldap/ctldap-ms/ctldap.js:497:81
Jan 31 21:36:27 feg-ldap-02 ctldap[2486]:     at Array.forEach (<anonymous>)
Jan 31 21:36:27 feg-ldap-02 ctldap[2486]:     at /home/ctldap/ctldap-ms/ctldap.js:495:11
Jan 31 21:36:27 feg-ldap-02 ctldap[2486]:     at tryCatcher (/home/ctldap/ctldap-ms/node_modules/bluebird/js/release/util.js:16:23)
Jan 31 21:36:27 feg-ldap-02 ctldap[2486]:     at Promise._settlePromiseFromHandler (/home/ctldap/ctldap-ms/node_modules/bluebird/js/release/promise.js:547:31)
Jan 31 21:36:27 feg-ldap-02 ctldap[2486]:     at Promise._settlePromise (/home/ctldap/ctldap-ms/node_modules/bluebird/js/release/promise.js:604:18)
Jan 31 21:36:27 feg-ldap-02 ctldap[2486]:     at Promise._settlePromiseCtx (/home/ctldap/ctldap-ms/node_modules/bluebird/js/release/promise.js:641:10)
Jan 31 21:36:27 feg-ldap-02 ctldap[2486]:     at _drainQueueStep (/home/ctldap/ctldap-ms/node_modules/bluebird/js/release/async.js:97:12)
Jan 31 21:36:27 feg-ldap-02 ctldap[2486]:     at _drainQueue (/home/ctldap/ctldap-ms/node_modules/bluebird/js/release/async.js:86:9)
Jan 31 21:36:27 feg-ldap-02 ctldap[2486]:     at Async._drainQueues (/home/ctldap/ctldap-ms/node_modules/bluebird/js/release/async.js:102:5)
Jan 31 21:36:27 feg-ldap-02 ctldap[2486]:     at Immediate.Async.drainQueues [as _onImmediate] (/home/ctldap/ctldap-ms/node_modules/bluebird/js/release/async.js:15:14)
Jan 31 21:36:27 feg-ldap-02 ctldap[2486]:     at processImmediate (internal/timers.js:464:21)```

This error is then fixed.

**Comment by djschilling** [comment]
@miltechniks which ldap call do you make so that that error occurs?

**Comment by milux** [comment]
> There was an error, as there has been some old code which wasn't adjusted as far as I've seen it.

I'm not sure whether this PR actually fixes something or makes the situation even worse.
You're most certainly overwriting the match function of the wrong filter here.
Maybe this achieves in some way what you want to do, but I wouldn't call this a fix...

I'm not absolutely sure about the fix I introduced upstream today with version 3.0.0, but at least I'm modifying the right prototype... :grimacing:

**Comment by miltechniks** [comment]
@djschilling I'm not sure, which request it is. There are a few requests when doing a login to a gitlab instance over LDAP. I can check that.

@milux I can also try the new version. Seems to be very similar. I'm not very familiar with JavaScript. ;-)
Thanks for your work.

**Pull request closed without merging**
